version: '3.7'

services:
  website:
    build:
      context: .
      dockerfile: ./build/website/Dockerfile
    image: secondtour-website
    container_name: secondtour-website
    restart: always
    volumes:
      - ./website:/app/website
    depends_on:
      - api
    networks:
      - back-network
    ports:
      - 8000:80
  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    image: secondtour-api
    container_name: secondtour-api
    restart: always
    volumes:
      - ./api:/app/api
    depends_on:
      - mysql
    networks:
      - back-network
    ports:
      - 44300:443
  mysql:
    build:
      context: .
      dockerfile: ./build/mysql/Dockerfile
    image: secondtour-mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: secondtour-mysql
    restart: always
    ports:
      - 33060:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: secondtour
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    networks:
      - back-network
networks:
  back-network: 
    driver: bridge
